### ISSUE TITLE
EXC_BAD_ACCESS Crash v2.13.0

### ISSUE THREAD

**Issue by dtroupe18** [muxinc/mux-stats-sdk-avplayer#153]
Hi, 

We have being using this SDK for several weeks now and our latest build has had two similar crashes come in that we were not seeing previously. These crashes are problematic because they are occurring at the start of video playback. Previously we were using SDK version `2.12.1` and we were not seeing these crashes. It also looks like the release notes for `2.13.0` 

> Deprecate old custom beaconDomain implementation and add new beaconCollectionDomain parameter that does not append the key to the url.

Might be related to the crash since the final line in the stacktrace is `-[MUXSDKEventQueue deduplicateBeaconData:]`. 

Here is the stacktrace as it appears in Xcode when viewing the crash:

<img width="402" alt="Screen Shot 2022-05-09 at 14 12 14" src="https://user-images.githubusercontent.com/15720032/167500611-a5273432-1938-4cc1-a20d-0f5093f744d7.png">

Here is the stacktrace we are seeing in BugSnag:

![Screen Shot 2022-05-09 at 14 13 00](https://user-images.githubusercontent.com/15720032/167500710-721dbefe-4017-4170-a3f4-52829a7ce3ef.png)

Crash is reported as 

>EXC_BAD_ACCESSMUXSDKCoreView
>Attempted to dereference garbage pointer 0x12b905e8a590.

and

>EXC_BAD_ACCESSMUXSDKViewData
>Attempted to dereference garbage pointer 0xdd2d38ec3800

We are seeing this in iOS `15.4.1`

For now we will revert to `2.12.1`, but please let me know if more information would be helpful 🙏

**Comment by nidhik** [comment]
Hi @dtroupe18! Thank you for reporting this issue. We are having trouble reproducing this crash. As far as we can tell, `deduplicateBeaconData` _should_ be unrelated to the custom beacon collection domain.  The following information would help us investigate further:
* Are you using the new `beaconCollectionDomain` parameter when encountering this crash? 
* Could you please share how you are calling `monitorAVPlayerLayer` in your application?
* Are there any steps to reproduce the issue, or perhaps a video source where this happens consistently?

Lastly, I believe this message `Attempted to dereference garbage pointer` indicates heap/memory corruption. It's possible another component outside of the Mux SDK is overwriting a location in memory used by the SDK, leading to this trace. It may be worthwhile to try some of the techniques listed here in order to get more information about the nature of the memory corruption: https://developer.apple.com/documentation/xcode/diagnosing-memory-thread-and-crash-issues-early

**Comment by dtroupe18** [comment]
@nidhik Thanks for looking into this. I believe you are correct - I reverted the SDK and I am still seeing crashes. Apologies for the noise. I'm going to close this issue.
