### ISSUE TITLE
UIWebview still found in mux sdk

### ISSUE THREAD

**Issue by 9now-video-apps** [muxinc/mux-stats-sdk-avplayer#53]
Hi there,

We are using mux in our app, the version we are using is 1.3.6, we are receiving warning about the UIWebview when we publish our app to the app store. 
`  pod 'Mux-Stats-AVPlayer', '1.3.6'
`

After checking the reference of the UIWebview followed by this post (https://levelup.gitconnected.com/how-to-find-and-remove-uiwebview-uses-in-your-ios-app-d9395f7baacc), we found that it seems MUXSDKStats and MuxCore are potentially still using the UIWebview.

`
for framework in Frameworks/*.framework; do
  fname=$(basename $framework .framework)
  echo $fname
  nm $framework/$fname | grep UIWebView
done
MUXSDKStats
MuxCore
`

Would you please have a look at this issue? Thanks.

Best regards,
Hai

**Comment by dylanjha** [comment]
Thanks for opening this Hai,

I took a close look at this a few months ago in #32. The situation is similar to Mapbox: https://github.com/mapbox/ios-sdk-examples/issues/373

  * We do not use `UIWebView` in this SDK nor in `Mux-Core`
  * The debug symbols `dSYM` that get generated have references to UIWebView because of the versions of iOS that we target

Again, the only mention of UIWebView that our framework makes is in the debug symbols, which does not contain any functional code. The warning is either overly aggressive or coming from another library that is actually using `UIWebView`

**Comment by 9now-video-apps** [comment]
Hi, @dylanjha,

Thank you for your reply. 

From the release comments for 1.3.6, we can see MUX is not using UI related components. We will do more investigating on our side. 
Meanwhile, would you mind do a quick verify that changing the target iOS version can remove the UIWebview reference? Thanks.

Best regards,
Hai

**Comment by wstringer-brain** [comment]
@dylanjha @9now-video-apps Experiencing the same problem. We are supporting 12.4.

**Comment by dylanjha** [comment]
@wstringer-brain Mux does not use UIWebView. The only thing in the Mux framework that mentions this is in the dSYM files that are used for debugging that do not contain any functional code.
